// بيانات تجريبية لأعمال علمية في مؤسسة ساعي
// — ٢٥ عملاً متنوع التخصص والمسار والمرحلة
// — تواريخ نسبية حول 2026-04-30 لإظهار حالات (مكتمل/قيد التنفيذ/متأخر)

import type { ScientificWork } from "@/types/works";

// تواريخ ثابتة بدلاً من Date.now() لاستقرار snapshot
const REF = "2026-04-30";

function daysFrom(base: string, days: number): string {
  const d = new Date(base);
  d.setDate(d.getDate() + days);
  return d.toISOString().slice(0, 10);
}

export const SAMPLE_WORKS: ScientificWork[] = [
  {
    id: "w-001",
    code: "SAEI-2024-001",
    title: "تحقيق كتاب \"المستصفى\" للإمام الغزالي",
    specialty: "USUL",
    track: "THESIS",
    researcher: "أ.د. عبدالله السالم",
    stage: "IN_PRODUCTION",
    progress: 88,
    startedAt: daysFrom(REF, -240),
    deadline: daysFrom(REF, 30),
  },
  {
    id: "w-002",
    code: "SAEI-2024-002",
    title: "شرح صحيح البخاري — كتاب الإيمان",
    specialty: "HADITH",
    track: "BOOK",
    researcher: "أ.د. خالد الفهد",
    stage: "WRITING",
    progress: 55,
    startedAt: daysFrom(REF, -180),
    deadline: daysFrom(REF, 90),
  },
  {
    id: "w-003",
    code: "SAEI-2024-003",
    title: "الصحيحة من الأحاديث في فضائل الأعمال",
    specialty: "HADITH",
    track: "BOOK",
    researcher: "د. سعيد الحربي",
    stage: "UNDER_REVIEW",
    progress: 76,
    startedAt: daysFrom(REF, -200),
    deadline: daysFrom(REF, 45),
  },
  {
    id: "w-004",
    code: "SAEI-2024-004",
    title: "تفسير سورة البقرة — دراسة موضوعية",
    specialty: "TAFSIR",
    track: "BOOK",
    researcher: "أ.د. منال القحطاني",
    stage: "WRITING",
    progress: 42,
    startedAt: daysFrom(REF, -150),
    deadline: daysFrom(REF, 120),
  },
  {
    id: "w-005",
    code: "SAEI-2024-005",
    title: "الإجماع عند الأصوليين — دراسة نقدية",
    specialty: "USUL",
    track: "THESIS",
    researcher: "د. محمد العتيبي",
    stage: "RESEARCH",
    progress: 22,
    startedAt: daysFrom(REF, -90),
    deadline: daysFrom(REF, 180),
  },
  {
    id: "w-006",
    code: "SAEI-2024-006",
    title: "النوازل المعاصرة في المعاملات المالية",
    specialty: "FIQH",
    track: "JOURNAL",
    researcher: "د. سعيد الحربي",
    stage: "PUBLISHED",
    progress: 100,
    startedAt: daysFrom(REF, -300),
    deadline: daysFrom(REF, -30),
  },
  {
    id: "w-007",
    code: "SAEI-2024-007",
    title: "تراجم أئمة القرن الرابع الهجري",
    specialty: "BIO",
    track: "BOOK",
    researcher: "أ. منال القحطاني",
    stage: "IN_PRODUCTION",
    progress: 92,
    startedAt: daysFrom(REF, -260),
    deadline: daysFrom(REF, 15),
  },
  {
    id: "w-008",
    code: "SAEI-2024-008",
    title: "السيرة النبوية — جوانب القيادة والإدارة",
    specialty: "SEERAH",
    track: "BOOK",
    researcher: "أ.د. خالد الفهد",
    stage: "UNDER_REVIEW",
    progress: 70,
    startedAt: daysFrom(REF, -210),
    deadline: daysFrom(REF, -10),
  },
  {
    id: "w-009",
    code: "SAEI-2024-009",
    title: "أحكام الزكاة في فقه المعاصرين",
    specialty: "FIQH",
    track: "ARTICLE",
    researcher: "د. عبدالله السالم",
    stage: "PUBLISHED",
    progress: 100,
    startedAt: daysFrom(REF, -200),
    deadline: daysFrom(REF, -60),
  },
  {
    id: "w-010",
    code: "SAEI-2024-010",
    title: "مصطلح الحديث عند الإمام مالك في الموطأ",
    specialty: "HADITH",
    track: "THESIS",
    researcher: "د. محمد العتيبي",
    stage: "WRITING",
    progress: 48,
    startedAt: daysFrom(REF, -160),
    deadline: daysFrom(REF, 60),
  },
  {
    id: "w-011",
    code: "SAEI-2024-011",
    title: "أصول العقيدة عند السلف الصالح",
    specialty: "AQEEDAH",
    track: "BOOK",
    researcher: "أ.د. عبدالله السالم",
    stage: "RESEARCH",
    progress: 18,
    startedAt: daysFrom(REF, -60),
    deadline: daysFrom(REF, 240),
  },
  {
    id: "w-012",
    code: "SAEI-2024-012",
    title: "مقال: الإعجاز البلاغي في القرآن الكريم",
    specialty: "ARABIC",
    track: "ARTICLE",
    researcher: "أ. منال القحطاني",
    stage: "PUBLISHED",
    progress: 100,
    startedAt: daysFrom(REF, -120),
    deadline: daysFrom(REF, -45),
  },
  {
    id: "w-013",
    code: "SAEI-2024-013",
    title: "موسوعة المصطلحات الأصولية المعاصرة",
    specialty: "USUL",
    track: "BOOK",
    researcher: "د. خالد الفهد",
    stage: "PROPOSED",
    progress: 5,
    startedAt: daysFrom(REF, -20),
    deadline: daysFrom(REF, 365),
  },
  {
    id: "w-014",
    code: "SAEI-2024-014",
    title: "الفقه المقارن في المعاملات الرقمية",
    specialty: "FIQH",
    track: "THESIS",
    researcher: "د. سعيد الحربي",
    stage: "WRITING",
    progress: 38,
    startedAt: daysFrom(REF, -130),
    deadline: daysFrom(REF, -5),
  },
  {
    id: "w-015",
    code: "SAEI-2024-015",
    title: "بحث: منهج الإمام النووي في شرح الحديث",
    specialty: "HADITH",
    track: "ARTICLE",
    researcher: "أ.د. منال القحطاني",
    stage: "UNDER_REVIEW",
    progress: 80,
    startedAt: daysFrom(REF, -90),
    deadline: daysFrom(REF, 20),
  },
  {
    id: "w-016",
    code: "SAEI-2024-016",
    title: "مدخل إلى علم التفسير الموضوعي",
    specialty: "TAFSIR",
    track: "BOOK",
    researcher: "د. محمد العتيبي",
    stage: "RESEARCH",
    progress: 25,
    startedAt: daysFrom(REF, -75),
    deadline: daysFrom(REF, 150),
  },
  {
    id: "w-017",
    code: "SAEI-2024-017",
    title: "تحقيق رسالة \"الفروق\" للقرافي",
    specialty: "USUL",
    track: "THESIS",
    researcher: "أ.د. خالد الفهد",
    stage: "IN_PRODUCTION",
    progress: 95,
    startedAt: daysFrom(REF, -280),
    deadline: daysFrom(REF, 10),
  },
  {
    id: "w-018",
    code: "SAEI-2024-018",
    title: "أئمة الجرح والتعديل — تراجم وموازنات",
    specialty: "BIO",
    track: "JOURNAL",
    researcher: "د. عبدالله السالم",
    stage: "PUBLISHED",
    progress: 100,
    startedAt: daysFrom(REF, -180),
    deadline: daysFrom(REF, -30),
  },
  {
    id: "w-019",
    code: "SAEI-2024-019",
    title: "العقيدة عند ابن تيمية — دراسة منهجية",
    specialty: "AQEEDAH",
    track: "THESIS",
    researcher: "د. سعيد الحربي",
    stage: "WRITING",
    progress: 60,
    startedAt: daysFrom(REF, -170),
    deadline: daysFrom(REF, 50),
  },
  {
    id: "w-020",
    code: "SAEI-2024-020",
    title: "غزوات الرسول ﷺ في ضوء العلوم العسكرية",
    specialty: "SEERAH",
    track: "BOOK",
    researcher: "أ. منال القحطاني",
    stage: "PROPOSED",
    progress: 8,
    startedAt: daysFrom(REF, -25),
    deadline: daysFrom(REF, 300),
  },
  {
    id: "w-021",
    code: "SAEI-2024-021",
    title: "البلاغة العربية في كتب التفسير",
    specialty: "ARABIC",
    track: "JOURNAL",
    researcher: "د. محمد العتيبي",
    stage: "UNDER_REVIEW",
    progress: 72,
    startedAt: daysFrom(REF, -110),
    deadline: daysFrom(REF, 25),
  },
  {
    id: "w-022",
    code: "SAEI-2024-022",
    title: "تخريج أحاديث كتاب \"الأذكار\" للنووي",
    specialty: "HADITH",
    track: "BOOK",
    researcher: "أ.د. عبدالله السالم",
    stage: "ARCHIVED",
    progress: 100,
    startedAt: daysFrom(REF, -540),
    deadline: daysFrom(REF, -200),
  },
  {
    id: "w-023",
    code: "SAEI-2024-023",
    title: "الفتاوى الجامعة للشيخ الغنيمان — تجميع وتوثيق",
    specialty: "FIQH",
    track: "BOOK",
    researcher: "أ.د. خالد الفهد",
    stage: "WRITING",
    progress: 35,
    startedAt: daysFrom(REF, -140),
    deadline: daysFrom(REF, -20),
  },
  {
    id: "w-024",
    code: "SAEI-2024-024",
    title: "مقدمة في علم أصول التفسير",
    specialty: "TAFSIR",
    track: "ARTICLE",
    researcher: "د. سعيد الحربي",
    stage: "PROPOSED",
    progress: 12,
    startedAt: daysFrom(REF, -30),
    deadline: daysFrom(REF, 200),
  },
  {
    id: "w-025",
    code: "SAEI-2024-025",
    title: "السنن المهجورة في العبادات اليومية",
    specialty: "FIQH",
    track: "JOURNAL",
    researcher: "أ. منال القحطاني",
    stage: "IN_PRODUCTION",
    progress: 90,
    startedAt: daysFrom(REF, -220),
    deadline: daysFrom(REF, 18),
  },
];
